# Generated by Django 4.1.1 on 2022-11-03 17:32

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("preview_img", models.CharField(max_length=200, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("content", martor.models.MartorField()),
                ("description", models.TextField(default="project preview...")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "DRAFT"), (1, "PUBLISH")], default=0
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
