# Generated by Django 4.1.1 on 2022-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default="post preview..."),
        ),
        migrations.DeleteModel(
            name="Preview",
        ),
    ]
