# Generated by Django 4.1.1 on 2022-10-27 13:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=martor.models.MartorField(),
        ),
    ]
