# Generated by Django 4.1.1 on 2022-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_description_delete_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="preview_img",
            field=models.CharField(
                default="https://i.imgur.com/czTlc33.jpg", max_length=200, unique=True
            ),
            preserve_default=False,
        ),
    ]
